name: Cats and dogs CI/CD

on:
  push:
    branches:
      - step**

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./cats_dogs_other/train/requirements.txt

      - name: Launch mlflow training in Openshift
        run: |
          export KUBE_MLFLOW_TRACKING_URI="${{vars.MLFLOW_TRACKING_URI}}"
          export MLFLOW_TRACKING_URI="${{vars.MLFLOW_TRACKING_URI}}"
          export MLFLOW_S3_ENDPOINT_URL="${{vars.MLFLOW_S3_ENDPOINT_URL}}"
          export AWS_ACCESS_KEY_ID="${{vars.AWS_ACCESS_KEY_ID}}"
          export AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}"

          cd cats_dogs_other/train
          mlflow run . \
            --experiment-name cats-dogs-other \
            --backend kubernetes \
            --backend-config kubernetes_config.json \
            -P split_ratio_train=0.7 \
            -P split_ratio_evaluate=0.2 \
            -P split_ratio_test=0.1 \
            -P batch_size=32 \
            -P epochs=6 \
            -P working_dir=./cats_dogs_other/train/dist
